name: "plan-terraform"

on:
  #push:
  #  branches:
  #    - main
  issue_comment:
  pull_request:
    secrets:
      VAULT_ROLE_ID:
        description: "The vault role id for authenticating with Vault"
        required: true
      VAULT_SECRET_ID:
        description: "The vault secret id for authenticating with Vault"
        required: true
      TERRAFORM_OPTS:
       description: 'The vars willing to pass to terraform plan example -var="image_id=ami-abc123"'
       required: false

jobs:
  terraform:
    name: "Terraform"
    runs-on: terraform-runner
    environment: just-eat-network-monitoring-prod
    defaults:
     run:
      working-directory: /runner/_work/enterprisetransitgateway/enterprisetransitgateway/
    permissions:
      pull-requests: write
      statuses: write
    if: |
      github.event.issue.pull_request != ''
      && startsWith(github.event.comment.body, '/plan')
    steps:
      # TODO: move to separate action
      # Use regex to parse the target passed with the /plan command on the PR comment
      - name: Get specified environment from comment
        id: get-selected-env
        uses: actions/github-script@v6
        with:
          script: |
            // Extract the deploy arguments from the trigger phrase containing these characters: a-z, A-Z, digits, hyphen
            const regex = /\/plan ([a-zA-Z\d\-]+)/;
            const arguments = regex.exec(context.payload.comment.body);
            core.info(`Arguments parsed: ${arguments}`);
            let awsEnv;
            if (arguments == null) {
              awsEnv = "${{ inputs.aws-env }}";
            } else {
              awsEnv = arguments[1];
            }
            core.info(`Target environment: ${awsEnv}`);
            return awsEnv;
          result-encoding: string

      # Due to how the triggers for comments work, the PR details must be retrieved first to correctly checkout the PR branch
      - name: Get Pull Request details
        uses: actions/github-script@v6
        id: get-pr
        with:
          script: |
            core.info(`Getting Pull Request #${context.issue.number} from ${context.repo.owner}/${context.repo.repo}`);
            try {
              const result = await github.rest.pulls.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number
              });
              return result.data;
            } catch (err) {
              core.setFailed(`Request failed with error ${err}`);
            }

      - name: Leave started notification
        uses: actions/github-script@v6
        with:
          script: |
            const awsEnv = "${{ steps.get-selected-env.outputs.result }}";
            const commitSha = "${{ fromJSON(steps.get-pr.outputs.result).head.sha }}"
            core.info(`Leaving start comment on #${context.issue.number} from ${context.repo.owner}/${context.repo.repo}`);
            core.info(`Targeting environment: ${awsEnv}`);
            try {
              const workflowUrl = `${{ github.server_url }}/${context.repo.owner}/${context.repo.repo}/actions/runs/${process.env.GITHUB_RUN_ID}`;
              // Leave started comment on the PR
              let message = `:rocket: [Terraform plan job](${workflowUrl}) to `;
              message += `${awsEnv}`;
              message += " has started. :hourglass:";
              message += "\n\n";
              message += "<details>\n";
              message += "<summary>Terraform plan help :sos:</summary>\n";
              message += "\n";
              message += "## Instructions\n";
              message += "\n";
              message += "Terraform plans are started by comments in GitHub pull requests.\n";
              message += "\n";
              message += "* Type `/plan` to start a new terraform plan to the default environment.\n";
              message += "* Type `/plan {environment name}` to start a new terraform plan to a specific environment.\n";
              message += "\n";
              message += "</details>\n";
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: message
              });

              // Add a commit status to the current commit
              const normalizedEnv = awsEnv.toLowerCase();
              const statusContext = `terraform-plan/${normalizedEnv}`;
              const description = `Terraform plan to ${normalizedEnv} has started...`;
              await github.rest.repos.createCommitStatus({
                owner: context.repo.owner,
                repo: context.repo.repo,
                sha: commitSha,
                state: 'pending',
                target_url: workflowUrl,
                description,
                context: statusContext
              });
            } catch (err) {
              core.setFailed(`Request failed with error ${err}`);
            }

      - name: Checkout code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          repository: ${{ fromJSON(steps.get-pr.outputs.result).head.repo.full_name }}
          ref: ${{ fromJSON(steps.get-pr.outputs.result).head.ref }}

      - name: Setup Terraform
        uses: github-actions/hashicorp-setup-terraform@v1
        with:
          terraform_wrapper: true
        #with:
          # terraform_version: 0.13.0:
          #cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          #github-token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Run tfenv
        run: >
          if test -f ".terraform-version"; then
            tfenv use;
          else
            tfenv use ${{ inputs.terraform-version }};
          fi

      - name: update NodeJS
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y nodejs
          sudo ln -s /usr/bin/nodejs /usr/local/bin/node
                
      - name: Terraform Init
        id: init
        run: terraform init #-force-copy ## only use force-copy if migrating from local state to S3 backend, not needed for new or existing projects
        
      - name: Terraform Format
        id: fmt
        run: terraform fmt -check -diff
        continue-on-error: true
        
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        #if: github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          terraform plan \
          -no-color \
          -input=false \
          ${{ secrets.TERRAFORM_OPTS }} \
          -out tf.plan \
          && terraform show -no-color tf.plan > /tmp/${{ steps.get-selected-env.outputs.result }}.txt

        continue-on-error: true

      - name: Set terraform plan env var
        run: |
          PLAN=$(cat /tmp/${{ steps.get-selected-env.outputs.result }}.txt)
          echo "PLAN<<EOF" >> "$GITHUB_ENV"
          echo "$PLAN" >> "$GITHUB_ENV"
          echo "EOF" >> "$GITHUB_ENV"
      
      - name: Create success comment
        uses: actions/github-script@v6
        with:
          script: |
            const awsEnv = "${{ steps.get-selected-env.outputs.result }}";
            const commitSha = "${{ fromJSON(steps.get-pr.outputs.result).head.sha }}"
            const output = `## Terraform plan for ${awsEnv}
            #### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialisation ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
            <details><summary>Show Plan</summary>
            \`\`\`tf\n
            ${process.env.PLAN}
            \`\`\`
            </details>
            *Pushed by: @${{ github.actor }}*`;
            try {
              const workflowUrl = `${{ github.server_url }}/${context.repo.owner}/${context.repo.repo}/actions/runs/${process.env.GITHUB_RUN_ID}`;
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: output
              })
              // Add a commit status to the current commit
              const normalizedEnv = awsEnv.toLowerCase();
              const statusContext = `terraform-plan/${normalizedEnv}`;
              const description = `Terraform plan to ${normalizedEnv} has succeeded.`;
              await github.rest.repos.createCommitStatus({
                owner: context.repo.owner,
                repo: context.repo.repo,
                sha: commitSha,
                state: 'success',
                target_url: workflowUrl,
                description,
                context: statusContext
              });
            } catch (err) {
              core.setFailed(`Request failed with error ${err}`);
            }
      
      - name: Leave failure notification
        uses: actions/github-script@v6
        if: ${{ failure() }}
        with:
          script: |
            const awsEnv = "${{ steps.get-selected-env.outputs.result }}";
            const commitSha = "${{ fromJSON(steps.get-pr.outputs.result).head.sha }}"
            core.info(`Leaving failure comment on #${context.issue.number} from ${context.repo.owner}/${context.repo.repo}`);
            core.info(`Targeting environment: ${awsEnv}`);
            try {
              const workflowUrl = `${{ github.server_url }}/${context.repo.owner}/${context.repo.repo}/actions/runs/${process.env.GITHUB_RUN_ID}`;
              // Leave failure comment on the PR
              let message = `:x: [Terraform plan](${workflowUrl}) to `;
              message += `${awsEnv}`;
              message += " has failed.";
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: message
              });
              // Add a commit status to the current commit
              const normalizedEnv = awsEnv.toLowerCase();
              const statusContext = `terraform-plan/${normalizedEnv}`;
              const description = `Terraform plan to ${normalizedEnv} has failed.`;
              await github.rest.repos.createCommitStatus({
                owner: context.repo.owner,
                repo: context.repo.repo,
                sha: commitSha,
                state: 'failure',
                target_url: workflowUrl,
                description,
                context: statusContext
              });
            } catch (err) {
              core.setFailed(`Request failed with error ${err}`);
            }
